
## Measures of spread

So far we've only been talk about the **typical** value, or the **central**
value, of a set data. But if you look at at @fig-hist-width you'll see two data
sets that are centred at the same value but have very different amounts of
variability. Both sets of data have a mean of 0. But, as you can see, the values
of one are spread out much more widely than the values of the other.

```{r}
#| echo: false
#| warning: false
#| label: fig-hist-width
#| fig-cap: Histogram of two distributions with equal means but different spreads. *N = 10,000* in each case.
dist_narrow <- rnorm(10000, mean = 0, sd = 1)
dist_wide <- rnorm(10000, mean = 0, sd = 3)
tibble::tibble(
  narrrow = dist_narrow,
  wide = dist_wide
) |>
  tidyr::pivot_longer(1:2) |>
  ggplot2::ggplot(aes(
    x = value,
    # group = name,
    fill = name,
    alpha = name
  )) +
  geom_histogram(color = "black", position = "identity") +
  scale_alpha_manual(values = c(1, 0.7), guide = "none") +
  scale_fill_manual(values = c("seagreen", "blue"), guide = "none") +
  NULL
```


This is why, in addition to measures of central tendency, we also need measures
that tell us about the spread, or _dispersion_ of a variable. Once again, there
are several measures of spread available, and we'll talk about five of them:

1. Range

2. Interquartile range

3. Deviation

4. Variance

5. Standard deviation

<!-- FIXME: Add the visualisation in here? -->


### Range

The **range** of a variable is simply the distance between its smallest and
largest values. For example, if we gather a sample of 100 participants and the
youngest one is 17 years old, and the oldest one is 67 years old, then the range
of our age variable in this sample if 67 - 15 = `r 67 - 17` years.

Checking the range of a variable can tell us something about whether our data
makes sense. Let's say that we've run a study examining reading ability in
primary school age children. In this study, we've also measured the ages of the
children. If the range of our age variable is, for example, 50 years, then that
tells us that we've measured _at least_ one person that is not school age.

Beyond that, the range doesn't tell us much of the information we'd usually like
to know. This is because the range is _extremely_ **sensitive to outliers**.
What this means is that it only takes one extreme value to inflate the range. In
our school example, it might be that all but one of the people measured is
actually in the correct age range. But the range alone cannot tell us if this is
the case.

### Interquartile range

A slightly more useful measure than the range is the **interquartile range** or
IQR. The IQR is the distance between the 1st and 3rd quartiles of the data.
Quartiles, like the name suggests, are created by splitting the data into four
chunks where each chunk has the same number of observations. Or put another way,
the median splits the data into two where half the observations are higher than
the median and half the observations are lower than the median. Quartiles are
created by taking each of these halves and splitting them in half again. The
range covered by the middle two 25% chunks is the IQR. It is the range that
covers the middle 50% of the data.

The benefit of the IQR over a simple range is that the IQR is not sensitive to
occasional extreme values. This is because the bottom 25% and the top 25% are
discarded. However, by discarding these data, the IQR provides no information
about how spread these outer areas are.

Both the range and the IQR work by looking at the distance between only two
observations in the entire data. For the range, it's the distance between the
minimum point and the maximum. For the IQR, it's the distance between the
midpoint of the upper half and the midpoint of the lower half. To get a more
fine-grained idea of the spread, we'll need a new way of measuring it. 

But that is where we'll leave it for now, and we'll pick our story back up in
the next lecture.



